[versions]
agp = "8.10.1"
kotlin = "2.0.21"
coreKtx = "1.10.1"
junit = "4.13.2"
junitVersion = "1.1.5"
espressoCore = "3.5.1"
appcompat = "1.6.1"
kotlinxCoroutinesCore = "1.8.1"
material = "1.10.0"
activity = "1.8.0"
constraintlayout = "2.1.4"
retrofit = "2.9.0"
gson = "2.9.0"
okhttp = "4.9.3"
preference = "1.1.1"
preferenceKtx = "1.2.1"
firebase_bom = "32.5.0"
lifecycleCommonJvm = "2.9.0"
swiperefreshlayout = "1.1.0"
workRuntimeKtx = "2.10.1"
firebaseMessaging = "24.1.1"
firebaseFirestore = "25.1.4"
mlkittext = "16.0.0"
konfetti = "2.0.2"
roomCompiler = "2.7.2"
roomRuntime = "2.7.2"
roomKtx = "2.7.2"
places = "4.3.1"
viewpager2 = "1.0.0"
annotations = "23.0.0"
media3CommonKtx = "1.7.1"
mpandroidchart = "3.1.0"
fragment = "1.8.8"


[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinxCoroutinesCore" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
androidx-activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
androidx-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
retrofit = { group = "com.squareup.retrofit2", name = "retrofit", version.ref = "retrofit" }
converter-gson = { group = "com.squareup.retrofit2", name = "converter-gson", version.ref = "retrofit" }
okhttp = { group = "com.squareup.okhttp3", name = "okhttp", version.ref = "okhttp" }
preference = { group = "androidx.preference", name = "preference", version.ref = "preference" }
androidx-preference-ktx = { group = "androidx.preference", name = "preference-ktx", version.ref = "preferenceKtx" }
firebase_bom = { group = "com.google.firebase", name = "firebase-bom", version.ref = "firebase_bom" }
firebase-auth = { group = "com.google.firebase", name = "firebase-auth-ktx" }
firebase-database = { group = "com.google.firebase", name = "firebase-database-ktx" }
firebase-firestore = { group = "com.google.firebase", name = "firebase-firestore", version.ref = "firebaseFirestore" }
firebase-messaging = { group = "com.google.firebase", name = "firebase-messaging", version.ref = "firebaseMessaging" }
mlkit-text = { group = "com.google.mlkit", name = "text-recognition", version.ref = "mlkittext" }
konfetti-xml = { module = "nl.dionsegijn:konfetti-xml", version.ref = "konfetti" }
androidx-lifecycle-common-jvm = { group = "androidx.lifecycle", name = "lifecycle-common-jvm", version.ref = "lifecycleCommonJvm" }
androidx-swiperefreshlayout = { group = "androidx.swiperefreshlayout", name = "swiperefreshlayout", version.ref = "swiperefreshlayout" }
androidx-work-runtime-ktx = { group = "androidx.work", name = "work-runtime-ktx", version.ref = "workRuntimeKtx" }
androidx-room-compiler = { group = "androidx.room", name = "room-compiler", version.ref = "roomCompiler" }
androidx-room-runtime = { group = "androidx.room", name = "room-runtime", version.ref = "roomRuntime" }
androidx-room-ktx = { group = "androidx.room", name = "room-ktx", version.ref = "roomKtx" }
places = { group = "com.google.android.libraries.places", name = "places", version.ref = "places" }
androidx-viewpager2 = { group = "androidx.viewpager2", name = "viewpager2", version.ref = "viewpager2" }
org-jetbrains-annotations = { group = "org.jetbrains", name = "annotations", version.ref = "annotations" }
androidx-media3-common-ktx = { group = "androidx.media3", name = "media3-common-ktx", version.ref = "media3CommonKtx" }
mpandroidchart = { group = "com.github.PhilJay", name = "MPAndroidChart", version.ref = "mpandroidchart" }
androidx-fragment = { group = "androidx.fragment", name = "fragment", version.ref = "fragment" }
androidx-fragment-ktx = { group = "androidx.fragment", name = "fragment-ktx", version.ref = "fragment" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
